# Copyright: 2016-2020 www.corvin.cn ROS小课堂
# Description:DWA局部规划器配置参数
# Author: corvin
# History:
#   20200413:init this file.
#
DWAPlannerROS:

#robot configuration params
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_th: 1.0

  max_vel_trans: 0.3
  min_vel_trans: 0.15

  max_vel_x: 0.2
  min_vel_x: -0.2

  max_vel_y: 0.2
  min_vel_y: -0.2

  max_vel_theta: 2.0
  min_vel_theta: 0.4

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 10
  vy_samples: 10
  vth_samples: 40
  controller_frequency: 4.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Global plan parameters
  prune_plan: true
